apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ys61e98ip-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ys61e98ip-nodejs 
  name: ys61e98ip-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ys61e98ip-nodejs 
